### ISSUE TITLE
Automate building HTML and PDF for draft proposal

### ISSUE THREAD

**Issue by AndyGlew** [riscv/riscv-CMOs#3]
Where my CMO proposal originally lived, AndyGlew/Ri5-stuff, I had a Makefile to do the build on the local machine I had cloned to.

Now this is moving to riscv/riscv-CMOs, it would be better to do something that all contributors can use, without having to install asciidoc, asciidoctor, kramdown and/or kramdoc on their machines.  I.e. server side.

(Also, ahem, I used tools in ~glew/bin ... {embarrassed shrug} )

**Comment by AndyGlew** [comment]
The riscv V vector spec does such automated builds, I think on checkins to the main branch

**Comment by dkruckemyer-work** [comment]
The pdf build flow has been resolved.
