### ISSUE TITLE
Can CMO extension support icache management?

### ISSUE THREAD

**Issue by weiqi7777** [riscv/riscv-CMOs#52]
I look CMO spec, and I feel that cmo don't manage icache.  
So I am confused.

**Comment by gfavor** [comment]
You are correct.  The CMO spec focuses on management of data caching.  The separate "I/D Consistency" extension that is in the works in the J group specifically focuses on management of instruction caching - especially in the context of self and cross modifying code (such as occurs with JIT'ed languages for example).

**Comment by weiqi7777** [comment]
thanks for your replay.
I will close this issue.
