### ISSUE TITLE
A puzzle about cbo.zero

### ISSUE THREAD

**Issue by baimengwei** [riscv/riscv-CMOs#53]
the following is the cbo.zero description:

A cbo.zero instruction performs **stores of zeros** to **the full set of bytes** corresponding to the cache block
whose effective address is the base address specified in rs1. The offset operand may be omitted; otherwise,
any expression that computes the offset shall evaluate to zero. An implementation may or may not update
**the entire set of bytes** atomically.

1.Why says that "may not update the entire set" ?  Is it conflict with "the full set of bytes" ?

2. Whether "stores of zeros" means that this instruction is equivalent to "store instruction", which need to maintain multi-core consistency.

**Comment by PhilNMcCoy** [comment]
The key is "may not update the entire set of bytes **atomically**".  It will update the entire set of bytes, but the update may not be atomic.
