### ISSUE TITLE
Clarify that implementations can perform a flush operation for CBO.INVAL (and CBO.CLEAN) 

### ISSUE THREAD

**Issue by dkruckemyer-work** [riscv/riscv-CMOs#56]
Request for a non-normative statement from https://github.com/riscv/riscv-profiles/issues/87

**Comment by tariqkurd-repo** [comment]
Hi @dkruckemyer-ventana did this go anywhere? It would be good to have the non-normative statement added

**Comment by gfavor** [comment]
@dkruckemyer-ventana You'll need to create a PR that the IC chairs can review and merge.  It is desirable to get this done soon as part of the ISA manuals' cleanup cycle that we are currently in.

**Comment by dkruckemyer-work** [comment]
Addressed in https://github.com/riscv/riscv-isa-manual/pull/1428
