### ISSUE TITLE
Does the prefetch.r instruction support specific cache levels?

### ISSUE THREAD

**Issue by Kepontry** [riscv/riscv-CMOs#63]
Prefetch instructions in X86 isa, such as `prefetcht0`, support prefetching the data into specific cache levels. Does the `prefetch.r` instruction in RISC-V support similar functions?

**Comment by ved-rivos** [comment]
Please see -
https://github.com/riscv/riscv-isa-manual/blob/main/src/zihintntl.adoc
regards
ved

**Comment by Kepontry** [comment]
Thanks a lot.
