### ISSUE TITLE
What access permission do CMO instructions require？

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-CMOs#64]
cbo.flush, cbo.clean and cbo.zero requires Read or Write or Execute permission？

**Comment by ingallsj** [comment]
Read Permission, according to this section of the spec (bold emphasis added):

> A cache-block management instruction is permitted to access the specified cache block **whenever a load
instruction** or store instruction is permitted to access the corresponding physical addresses. If neither a load
instruction nor store instruction is permitted to access the physical addresses, but an instruction fetch is
permitted to access the physical addresses, whether a cache-block management instruction is permitted to access
the cache block is UNSPECIFIED.
