### ISSUE TITLE
Is there a required/suggested legalization value for writing xenvcfg.CBIE to 2'b10?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-CMOs#65]
Hello,

The xenvcfg.CBIE has a reserved value of 2'b10. Thus, writing the reserved value 2'b10, an implementation should legalize to another legal value.

Is there a required/suggested legalization value for writing xenvcfg.CBIE to 2'b10?

Thank you.

![image](https://github.com/riscv/riscv-CMOs/assets/39526191/9cff9828-2a40-4b1a-9bab-d7a559bb9771)

**Comment by gfavor** [comment]
As with WARL fields in general, there is no required or suggested legalization value.  So you're free to choose whatever you think is best.  One view would say to legalize to the conservative (and all 0's) value that raises an exception on CBO.INVAL usage - for the sake of more readily catching what one would probably consider to be a programming error.

**Comment by YenHaoChen** [comment]
Thank you.
