### ISSUE TITLE
Integration of CMO spec into Unpriv spec as a chapter.

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-CMOs#66]
I'd like to request review of the CMO spec chapter as an integrated chapter within the Unprivileged spec.  You can review the PDF of the Unpriv spec [here](https://github.com/riscv/riscv-isa-manual/actions/runs/7891718802/artifacts/1242624765).

**Comment by ingallsj** [comment]
❌ 
>  Failed to generate URL to download artifact.  
> The following artifacts have expired and are no longer able to be downloaded.

Looking at https://github.com/riscv/riscv-isa-manual/blob/d28d56b5225ae44c811fa1422758e0e951edddc0/src/cmo.adoc from https://github.com/riscv/riscv-isa-manual/pull/1226 instead.

**Comment by wmat** [comment]
@ingallsj thanks, here's a PDF I just generated of Unpriv with CMO included: https://github.com/riscv/riscv-isa-manual/actions/runs/7992532593/artifacts/1263639081

**Comment by wmat** [comment]
@ingallsj were you able to view the PDF.  I'd like to merge cmo into the Unpriv spec asap.  Thanks.  Note that any additions or rewrites from a content perspective can be done against the Unpriv spec post merge.

**Comment by ingallsj** [comment]
Yes, I was, and LGTM

**Comment by wmat** [comment]
Please note that CMO has been integrated into top-of-tree of the Unprivileged spec.  Any changes to the CMO spec should be made against the riscv-isa-manual repo.  This repository will be archived.
