### ISSUE TITLE
Must cbo.clean, cbo.flush, and cbo.inval raise exception on an address in vacant region?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-CMOs#67]
Hello,

I want to clarify the permissions for cache-block management instructions. Consider a vacant region that PMP/PMA permits access to. Does any cache-block management instruction raise an exception on a cache block in that vacant region? Or should an implementation treat the instruction as nop in this case?

![image](https://github.com/riscv/riscv-CMOs/assets/39526191/6815c769-ce9a-4c0b-a224-d431e58801d4)

**Comment by ingallsj** [comment]
> Consider a vacant region that PMP/PMA permits access to.

A vacant region is defined in the Privileged ISA spec as PMA **not** supporting access to.

> Vacant regions are also classified as I/O regions but with attributes specifying that **no accesses are supported**.

**Comment by YenHaoChen** [comment]
Thank you for the clarification. Therefore, for an incorrect PMA configuration that allows access to vacant regions—whether due to a buggy software setting or hardware implementation—we indeed classify it as unspecified behavior when accessing addresses within these regions. Is this understanding accurate?

**Comment by ingallsj** [comment]
Buggy behavior is unspecified in the ISA.

**Comment by YenHaoChen** [comment]
Thank you.
